repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: no-commit-to-branch
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args:
          - --fix
          - --verbose
      - id: ruff-format

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks

  # add pylint to pre-commit hooks (use ./.pylintrc)
  - repo: https://github.com/PyCQA/pylint
    rev: v3.2.6
    hooks:
      - id: pylint
        args:
          - --rcfile=./.pylintrc
          - --fail-under=9.5
          - --exit-zero
