services:
  test_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: test_bot
    container_name: test_bot
    volumes:
      - ./logs:/app/logs:rw
    networks:
      - test_bot
    user: user
networks:
  test_bot:
    driver: bridge
