services:
  test_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: test_bot
    container_name: test_bot
    volumes:
      - ./logs:/app/logs:rw
      - /usr/bin:/usr/bin # Mount the /usr/bin directory
    devices:
      - /dev/vcio
    environment:
      - LD_LIBRARY_PATH=/usr/lib
    restart: on-failure:10
