services:
  test_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: test_bot
    container_name: test_bot
    volumes:
      - ./logs:/app/logs:rw
    networks:
      test_bot_net:
        ipv4_address: 172.18.0.2
    user: user
    environment:
      - FILE_API_URL=172.18.0.3
    depends_on:
      - file_api
    restart: on-failure:10

  file_api:
    build:
      context: api
      dockerfile: Dockerfile
    image: file_api
    container_name: file_api
    networks:
      test_bot_net:
        ipv4_address: 172.18.0.3
    volumes:
      - /opt/arcaea/assets:/opt/arcaea/assets

networks:
  test_bot_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16