version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot
    container_name: bot
    command: python app.py
    env_file:
      - env/docker.env
    volumes:
      - ./logs:/app/logs
    user: ${DOCKER_USER}
