services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot
    container_name: bot
    volumes:
      - ./logs:/app/logs:rw
      - /usr/bin:/usr/bin # Mount the /usr/bin directory
    devices:
      - /dev/vcio
    environment:
      - LD_LIBRARY_PATH=/usr/lib
    restart: on-failure:10
