services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot
    container_name: bot
    volumes:
      - ./logs:/app/logs:rwz
      - /usr/bin:/usr/bin # Mount the /usr/bin directory
    devices:
      - /dev/vcio
    environment:
      - LD_LIBRARY_PATH=/usr/lib
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - OWNER_ID=${OWNER_ID}
      - TEST_CHANNEL_ID=${TEST_CHANNEL_ID}
      - LEETCODE_CSRFTOKEN=${LEETCODE_CSRFTOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: on-failure:10
    user: "1000:1000"
