services:
  test_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: test_bot
    container_name: test_bot
    volumes:
      - ./logs:/app/logs:rw
      - /opt/arcaea/assets:/opt/arcaea/assets
      - /home/c8763yee/mygo-anime:/home/user/mygo-anime

    networks:
      test_bot_net:
        ipv4_address: 172.18.0.2
    user: user
    environment:
      - FILE_API_URL=172.18.0.3

    restart: on-failure:10

networks:
  test_bot_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
