services:
  bot:
    extends:
      file: docker-compose.yml
      service: test_bot
    image: bot
    container_name: bot
    volumes:
      - $HOME/logs:/app/logs:rw
      - /usr/bin:/usr/bin # Additional volume mount not in base
    devices:
      # Mount the /dev/vcio device for the Raspberry Pi
      - /dev/vcio

    environment:
      - DEBUG=False
    restart: on-failure:10
