services:
  test_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: test_bot
    container_name: test_bot
    volumes:
      - ./logs:/app/logs:rw
      - /opt/arcaea/assets:/opt/arcaea/assets
      - $HOME/mygo-anime:/home/user/mygo-anime
    user: user
    environment:
      - IS_DOCKER=True
      - DEBUG=True
      - MYSQL_HOST=host.docker.internal
    restart: on-failure:10
    extra_hosts:
      - "host.docker.internal:host-gateway"