name: Docker Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Deploy to Docker
        run: docker compose up -d