name: Docker Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .


      - name: Deploy to Docker
        run: docker compose up -d