name: Docker Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t bot .

      - name: Deploy to Docker with secret
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
          TEST_CHANNEL_ID: ${{ secrets.TEST_CHANNEL_ID }}
          LEETCODE_CSRFTOKEN: ${{ secrets.LEETCODE_CSRFTOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MQTT_BROKER: ${{ secrets.MQTT_BROKER }}
          ARCAEA_EMAIL: ${{ secrets.ARCAEA_EMAIL }}
          ARCAEA_PASSWORD: ${{ secrets.ARCAEA_PASSWORD }}
        run: docker compose -f docker-compose-ci.yml up -d