name: Docker Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .


      - name: Deploy to Docker with secret
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          LEETCODE_CSRFTOKEN: ${{ secrets.LEETCODE_CSRFTOKEN }}
          MQTT_BROKER: ${{ secrets.MQTT_BROKER }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
          TEST_CHANNEL_ID: ${{ secrets.TEST_CHANNEL_ID }}
          
        run: docker compose up -d